import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useInquiry } from "@/contexts/InquiryContext";
import { validateCheckoutFields } from "@/lib/checkoutValidation";
import { supabase } from "@/lib/supabase";
import { CheckCircle2, ChevronRight, Loader2, MapPin, Phone, ShoppingBag, UserRound } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

export default function Checkout() {
  const [, navigate] = useLocation(); const { items, total, clear } = useInquiry(); const [customerName, setCustomerName] = useState(""); const [phone, setPhone] = useState(""); const [address, setAddress] = useState(""); const [orderId, setOrderId] = useState<string>(); const [submitting, setSubmitting] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); const validationError = validateCheckoutFields({ fullName: customerName, phone, address }); if (validationError) return toast.error(validationError); if (items.some(item => !item.variantId)) return toast.error("اختر المقاس واللون قبل تأكيد الطلب."); setSubmitting(true); const { data, error } = await supabase.rpc("place_order", { p_full_name: customerName, p_phone: phone, p_address: address, p_items: items.map(item => ({ variant_id: item.variantId, quantity: item.quantity })) }); setSubmitting(false); if (error) return toast.error("تعذّر حفظ الطلب. قد يكون أحد الخيارات نفد من المخزون."); clear(); setOrderId(data as string); }
  if (orderId) return <main className="checkout-page"><div className="container checkout-confirmation"><CheckCircle2 size={64} /><span className="eyebrow">ATEF SHOES · شكراً لثقتك</span><h1>تم استلام طلبك بنجاح</h1><p>طلبك رقم <b>#{orderId.slice(0, 8).toUpperCase()}</b> قيد الانتظار الآن. سيتواصل معك فريق عاطف لتأكيد التفاصيل قبل الشحن.</p><div className="confirmation-badge">الدفع عند الاستلام · قيد الانتظار</div><Link href="/" className="checkout-back">العودة إلى المتجر</Link></div></main>;
  if (!items.length) return <main className="checkout-page"><div className="container checkout-empty"><ShoppingBag size={42} /><h1>سلة المشتريات فارغة</h1><p>أضف المنتجات التي تفضلها أولاً ثم عُد لإتمام الطلب.</p><Link href="/" className="checkout-back">تصفح المنتجات</Link></div></main>;
  return <main className="checkout-page" dir="rtl"><div className="container checkout-breadcrumb"><Link href="/">الرئيسية</Link><ChevronRight size={14} /><b>إتمام الطلب</b></div><div className="container checkout-layout"><form className="checkout-form" onSubmit={submit}><div className="checkout-title"><span className="eyebrow">الخطوة الأخيرة</span><h1>أكمل طلبك</h1><p>سيتم التواصل معك لتأكيد العنوان وموعد التوصيل.</p></div><div className="checkout-field"><Label htmlFor="customerName"><UserRound size={16} /> الاسم بالكامل</Label><Input id="customerName" required value={customerName} onChange={event => setCustomerName(event.target.value)} placeholder="اكتب اسمك بالكامل" /></div><div className="checkout-field"><Label htmlFor="phone"><Phone size={16} /> رقم الموبايل</Label><Input id="phone" required type="tel" value={phone} onChange={event => setPhone(event.target.value)} placeholder="0100 000 0000" /></div><div className="checkout-field"><Label htmlFor="address"><MapPin size={16} /> العنوان بالتفصيل - المحافظة والمنطقة</Label><Textarea id="address" required value={address} onChange={event => setAddress(event.target.value)} placeholder="المحافظة، المنطقة، الشارع، رقم العمارة والشقة" /></div><div className="payment-method"><div><b>طريقة الدفع</b><span>اختيار آمن ومريح عند استلام طلبك</span></div><strong>الدفع عند الاستلام</strong></div><Button className="place-order" type="submit" disabled={submitting}>{submitting ? <Loader2 className="animate-spin" /> : <CheckCircle2 size={18} />} تأكيد الطلب</Button></form><aside className="checkout-summary"><div className="summary-title"><ShoppingBag size={18} /><h2>ملخص الطلب</h2></div>{items.map(item => <article key={`${item.id}-${item.variantId}-${item.size}-${item.color}`} className="summary-item"><img src={item.imageUrl} alt="" /><div><b>{item.title}</b><span>{item.size && item.size !== "N/A" ? `مقاس ${item.size}` : "بدون مقاس"} · {item.color} · {item.quantity} قطعة</span><strong>{(item.price * item.quantity).toLocaleString("ar-EG")} ج.م</strong></div></article>)}<div className="summary-total"><span>الإجمالي</span><b>{total.toLocaleString("ar-EG")} ج.م</b></div></aside></div></main>;
}
