import { Button } from "@/components/ui/button";
import { useInquiry } from "@/contexts/InquiryContext";
import { createWhatsAppOrderLink } from "@/lib/whatsapp";
import { fetchCatalogProduct, type SupabaseCatalogProduct } from "@/lib/supabaseCatalog";
import { cn } from "@/lib/utils";
import { ArrowRight, Check, ChevronRight, Loader2, Minus, Plus, ShoppingBag, Tag, Truck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";

const categoryLabels: Record<string, string> = { men: "الأحذية الرجالي", women: "الأحذية الحريمي", kids: "أحذية الأطفال", bags: "الشنط والحقائب", offers: "العروض والخصومات" };
const whatsappNumber = (import.meta.env.VITE_STORE_WHATSAPP_NUMBER as string | undefined) || "201007891081";
const placeholder = "https://placehold.co/800x800/f5ede2/6b1d2f?text=ATEF+SHOES";

export default function ProductDetails() {
  const [, params] = useRoute("/products/:id"); const [, navigate] = useLocation(); const { addItem } = useInquiry();
  const [product, setProduct] = useState<SupabaseCatalogProduct | null>(); const [failed, setFailed] = useState(false); const [size, setSize] = useState<string>(); const [color, setColor] = useState<string>(); const [quantity, setQuantity] = useState(1); const [activeImage, setActiveImage] = useState<string>();
  useEffect(() => { if (!params?.id) return; setProduct(undefined); setFailed(false); void fetchCatalogProduct(params.id).then(item => { if (!item) setFailed(true); else { setProduct(item); const first = item.product_variants.find(variant => variant.stock_quantity > 0) ?? item.product_variants[0]; setSize(first?.size); setColor(first?.color); setActiveImage([...item.product_images].sort((a, b) => a.sort_order - b.sort_order)[0]?.public_url || placeholder); } }).catch(() => setFailed(true)); }, [params?.id]);
  const gallery = useMemo(() => product ? ([...product.product_images].sort((a, b) => a.sort_order - b.sort_order).map(image => image.public_url).filter(Boolean).concat(product.product_images.length ? [] : [placeholder])) : [], [product]);
  const sizes = useMemo(() => product ? Array.from(new Set(product.product_variants.map(variant => variant.size))) : [], [product]);
  const colors = useMemo(() => product ? Array.from(new Set(product.product_variants.filter(variant => !size || variant.size === size).map(variant => variant.color))) : [], [product, size]);
  const variant = product?.product_variants.find(item => item.size === size && item.color === color); const inStock = Boolean(variant && variant.stock_quantity > 0); const displayPrice = product ? Number(product.sale_price ?? product.price) : 0;
  useEffect(() => { if (colors.length && !colors.includes(color ?? "")) setColor(colors[0]); }, [colors, color]);
  if (product === undefined) return <main className="detail-state"><Loader2 className="animate-spin" /> جاري تحميل المنتج...</main>;
  if (failed || !product) return <main className="detail-state error">لم نتمكن من العثور على هذا المنتج.</main>;
  const addToCart = () => { if (!variant) return; addItem({ id: product.id, variantId: variant.id, title: product.title, price: displayPrice, imageUrl: gallery[0] || placeholder, size, color }, quantity); };
  const whatsappLink = createWhatsAppOrderLink({ phone: whatsappNumber, productTitle: product.title, size: size ?? "N/A", color: color ?? "غير محدد" });
  return <main className="product-detail-page" dir="rtl"><div className="container detail-breadcrumb"><Link href="/">الرئيسية</Link><ChevronRight size={14} /><span>{categoryLabels[product.category] ?? "المنتجات"}</span><ChevronRight size={14} /><b>{product.title}</b></div><div className="container detail-layout"><div className="detail-gallery"><div className="detail-image"><img src={activeImage ?? gallery[0] ?? placeholder} alt={product.title} /><span className="image-caption">ATEF SHOES · 1969</span></div><div className="gallery-thumbnails">{gallery.map((image, index) => <button key={`${image}-${index}`} className={cn(activeImage === image && "active")} aria-label={`عرض الصورة ${index + 1}`} onClick={() => setActiveImage(image)}><img src={image} alt="" /></button>)}</div></div><div className="detail-copy"><span className="detail-category">{categoryLabels[product.category]}</span><div className="detail-stock">{inStock ? <><i /> متوفر في المخزون</> : "نفدت الكمية حالياً"}</div><h1>{product.title}</h1><div className="detail-price"><b>{displayPrice.toLocaleString("ar-EG")} <small>ج.م</small></b>{product.sale_price && <><del>{Number(product.price).toLocaleString("ar-EG")} ج.م</del><span><Tag size={13} /> عرض خاص</span></>}</div><p className="detail-description">{product.description}</p><div className="selector-block"><div className="selector-heading"><b>اختاري المقاس</b><span>{product.category === "bags" ? "هذا المنتج لا يحتاج مقاساً" : "مقاس مصري"}</span></div><div className="selector-options">{sizes.map(item => <button key={item} className={cn(size === item && "selected")} onClick={() => setSize(item)}>{item === "N/A" ? "بدون مقاس" : item}{size === item && <Check size={13} />}</button>)}</div></div><div className="selector-block"><div className="selector-heading"><b>اختاري اللون</b><span>{color}</span></div><div className="color-options">{colors.map(item => <button key={item} className={cn(color === item && "selected")} onClick={() => setColor(item)}><i className={`swatch swatch-${item}`} />{item}</button>)}</div></div><div className="detail-benefits"><span><Truck size={17} /> توصيل لجميع المحافظات</span><span><Check size={17} /> الدفع عند الاستلام</span></div><div className="detail-actions"><div className="quantity-control large"><button onClick={() => setQuantity(current => Math.max(1, current - 1))}><Minus size={15} /></button><b>{quantity}</b><button onClick={() => setQuantity(current => Math.min(variant?.stock_quantity || 1, current + 1))}><Plus size={15} /></button></div><Button className="add-cart-button" disabled={!inStock} onClick={addToCart}><ShoppingBag size={18} /> أضف إلى السلة</Button></div><a className="whatsapp-button detail-whatsapp" href={whatsappLink} target="_blank" rel="noreferrer"><span>اطلب مباشرة عبر واتساب</span><ArrowRight size={18} /></a><button className="back-link" onClick={() => navigate("/")}>العودة للتسوق</button></div></div></main>;
}
